version: '3.9'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bettingapp
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: node index.js
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge